### ISSUE TITLE
movie summary

### ISSUE THREAD

**Issue by wunderkinnd** [alvaro-octal/TMDB-PHP-API#10]
hello,
is it possible to get the movie-description?
Thanks

**Comment by Alvaroctal** [comment]
It seems I fully forgot about that field, can't understand. (this project is "a bit" abandoned anyway)

I guess you can use the generic [get method](https://code.octal.es/php/tmdb-api/source-class-Movie.html#152-161).

```php
$movie->get('overview');
```

**Comment by wunderkinnd** [comment]
Thank you for your fast response,
well, I think, it will not work that easy.
Is it a lot of work to add this function to your code? I just need a description of the movies (in german) as it is shown on the tmdb-movie-pages. your code works fine and I dont't want to change the api-wrapper, if it isn't necessary.

**Comment by Alvaroctal** [comment]
You have to specify the language when you instance the `TMDB Object`, take a [look](https://github.com/Alvaroctal/TMDB-PHP-API/blob/master/tmdb-api.php#L125).

So, if I have understood your problem would be:

```php
$tmdb = new TMDB($apikey, 'de', true);
```

Anyway, you should keep in mind that, when you get a `movie` object with a search method this object is incomplete, some attributes like the overview may not be present, in order to load them you have get the movie by it's id.
